# Generated by Django 4.1.7 on 2023-04-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="gaming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("categori", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=50)),
                ("size", models.BigIntegerField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(name="ghaming",),
    ]
