# Generated by Django 4.1.7 on 2023-04-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_gaming_delete_ghaming"),
    ]

    operations = [
        migrations.RemoveField(model_name="gaming", name="size",),
    ]
