# Generated by Django 4.1.7 on 2023-04-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_remove_gaming_size"),
    ]

    operations = [
        migrations.AlterModelTable(name="gaming", table="myapp_gaming",),
    ]
