# Generated by Django 4.1.7 on 2023-04-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_gaming_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="maping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("size", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
            ],
            options={"db_table": "myapp_maping",},
        ),
    ]
